[package]
name = "api-gateway"
version = "0.1.0"
authors = ["Simone Romano <simoneromano@protonmail.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web="^1.0.8"
actix-rt="^0.2.5"
futures="^0.1.29"
actix-http="^0.2.10"
lazy_static="^1.4.0"
actix-multipart="^0.1.4"
reqwest="^0.9.22"
url="2.1.0"
bytes="0.4.12"