version: "3.6"

services:
  # MYSQL
  mysql:
    image: mariadb
    restart: unless-stopped
    expose:
      - 3306
    environment:
      # MYSQL_ROOT_PASSWORD: example
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: coffeed
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - coffeed-network

  # Database GUI
  adminer:
    image: adminer
    restart: always
    ports:
      - 801:8080
    networks:
      - coffeed-network

  # Redis
  redis:
    image: redis
    restart: unless-stopped
    expose:
      - 6379
    networks:
      - coffeed-network

  # Rust Microservices
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: ./.docker/api-gateway.dockerfile
    restart: unless-stopped
    networks:
      - coffeed-network
    env_file:
      - ./.env

  auth-service:
    build:
      context: ./auth-service
      dockerfile: ./.docker/auth-service.dockerfile
    restart: unless-stopped
    networks:
      - coffeed-network
    env_file:
      - ./.env

  upload-service:
    build:
      context: ./upload-service
      dockerfile: ./.docker/upload-service.dockerfile
    restart: unless-stopped
    networks:
      - coffeed-network
    env_file:
      - ./.env
    volumes:
      - ./public:/upload-service/public

networks:
  coffeed-network:

volumes:
  redis_data:
  mysql_data:
