version: "3.6"

services:
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: username
      ME_CONFIG_MONGODB_ADMINPASSWORD: password

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: ./.docker/api-gateway.dockerfile
    restart: unless-stopped
    networks:
      - api_network
    env_file:
      - ./api-gateway/.env
    ports:
      - 8081:80

  upload-service:
    build:
      context: ./upload-service
      dockerfile: ./.docker/upload-service.dockerfile
    restart: unless-stopped
    networks:
      - api_network
    env_file:
      - ./upload-service/.env
    # ports:
    #   - 8082:80

networks:
  api_network:
